Upgrade and change currently used codemirror libraries
silk-framework/silk pull request #827
Opened 2024-09-25 15:03 UTC by arausly

2024-09-30 15:19 UTC, haschek requested changes

2024-10-02 10:32 UTC, arausly commented on workspace/src/app/views/shared/Metadata/Metadata.tsx
> +                                <CodeEditor
Didn't seem necessary any more

2024-10-29 11:00 UTC, arausly commented on workspace/test/integration/components/CreateArtefactModal/CreateArtefactModal.test.tsx
> +        // expect(metaData.description).toBe("Some description"); //todo find solution to inserting "refed" codemirror6 desc
Created follow up issue regarding this, see [here](https://jira.eccenca.com/browse/CMEM-6208)

2024-10-29 11:00 UTC, arausly commented on workspace/test/integration/components/CreateArtefactModal/CreateArtefactModal.test.tsx
> +        //     expect(findSingleElement(wrapper, "#restrictionParam").text()).toContain("restriction value") //fixme
Created follow up issue regarding this, see [here](https://jira.eccenca.com/browse/CMEM-6208)

2024-10-30 15:37 UTC, haschek approved these changes

2024-10-30 15:37 UTC, merged